---
title: "About Me"
---

I am a master's student at UC Santa Barbara's Bren School of Environmental Science & Management, specializing in conservation planning. I am passionate about using data science and geospatial analysis to inform conservation and management decisions.

Prior to graduate school, I worked as a consulting wildlife biologist and botanist conducting special status species surveys, botanical surveys, and biological construction monitoring. I have experience working with a variety of taxa, including the federally and state listed California tiger salamader (*Ambystoma californiense*) and California red-legged frog (*Rana draytonii*). I have also worked on habitat restoration projects, including invasive species removal, native plant installation, and habitat restoration monitoring. I also hold a B.S. in Environmental Studies from UCSB. 

I am from Valley Center, a small town in north county San Diego, where I fell in love with nature. In my free time I enjoy bird watching, botanizing, hiking, and running. 

## Professional Affiliations

[California Native Plant Society](https://www.cnps.org/) \| [The Wildlife Society](https://wildlife.org/cali-centralcoast/)
